package Constants;

public interface Constants {
    String LOG_TAG = "SmartHome";
    String DEVICE_NAME = "DeviceName";
    String APPLIANCE_LIST = "APPLIANCE_LIST";
    String MENU_CLICK_LISTENER = "MENU_CLICK_LISTENER";

    String SWITCH_BOARD_TYPE = "SWITCH_BOARD_TYPE";
    String SWITCH_BOARD_SIX_MODULAR_TYPE = "SWITCH_BOARD_SIX_MODULAR_TYPE";
    String SWITCH_BOARD_FOUR_MODULAR_TYPE = "SWITCH_BOARD_FOUR_MODULAR_TYPE";
    String SWITCH_BOARD_TWO_MODULAR_TYPE = "SWITCH_BOARD_TWO_MODULAR_TYPE";

    int NUMBER_SWITCHES_SIX_MODULAR = 6;
    int NUMBER_SWITCHES_FOUR_MODULAR = 4;
    int NUMBER_SWITCHES_TWO_MODULAR = 2;

    String DEVICE_TYPE_ELECTRIC_LIGHT = "DEVICE_TYPE_ELECTRIC_LIGHT";
    String DEVICE_TYPE_ELECTRIC_FAN = "DEVICE_TYPE_ELECTRIC_FAN";
}
